//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Executor.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadosTreinamento
    {
        public DadosTreinamento()
        {
            this.TreinamentoDados = new HashSet<TreinamentoDados>();
        }
    
        public int Codigo { get; set; }
        public byte[] Dados { get; set; }
        public int Elemento { get; set; }
        public byte[] FiguraOriginal { get; set; }
    
        public virtual Elemento Elemento1 { get; set; }
        public virtual ICollection<TreinamentoDados> TreinamentoDados { get; set; }
    }
}
