//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Executor.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadosRedeNeural
    {
        public DadosRedeNeural()
        {
            this.Treinamento = new HashSet<Treinamento>();
        }
    
        public int Codigo { get; set; }
        public int NumeroNeuroniosEntrada { get; set; }
        public int NumeroNeuroniosOculta { get; set; }
        public int NumeroNeuroniosSaida { get; set; }
        public byte[] Pesos { get; set; }
    
        public virtual ICollection<Treinamento> Treinamento { get; set; }
    }
}
