//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Executor.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTreinamento
    {
        public int Treinamento { get; set; }
        public int Geracao { get; set; }
        public double MargemErro { get; set; }
    
        public virtual Treinamento Treinamento1 { get; set; }
    }
}
