//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Executor.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonografiaEntities : DbContext
    {
        public MonografiaEntities()
            : base("name=MonografiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Algoritmo> Algoritmo { get; set; }
        public DbSet<DadosRedeNeural> DadosRedeNeural { get; set; }
        public DbSet<DadosTreinamento> DadosTreinamento { get; set; }
        public DbSet<DadosValidacao> DadosValidacao { get; set; }
        public DbSet<Elemento> Elemento { get; set; }
        public DbSet<Treinamento> Treinamento { get; set; }
        public DbSet<TreinamentoDados> TreinamentoDados { get; set; }
        public DbSet<ValidacaoDados> ValidacaoDados { get; set; }
        public DbSet<RedeNeuralResultante> RedeNeuralResultante { get; set; }
        public DbSet<LogTreinamento> LogTreinamento { get; set; }
    }
}
