//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Executor.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treinamento
    {
        public Treinamento()
        {
            this.TreinamentoDados = new HashSet<TreinamentoDados>();
            this.Validacao = new HashSet<ValidacaoDados>();
            this.LogTreinamento = new HashSet<LogTreinamento>();
        }
    
        public int Codigo { get; set; }
        public int Algoritmo { get; set; }
        public int NumeroGeracoes { get; set; }
        public double Momentum { get; set; }
        public double TaxaAprendizado { get; set; }
        public int DadosRedeNeural { get; set; }
        public bool MinimoLocal { get; set; }
        public int RedeNeuralResultante { get; set; }
        public int NumeroExemplos { get; set; }
    
        public virtual Algoritmo Algoritmo1 { get; set; }
        public virtual DadosRedeNeural DadosRedeNeural1 { get; set; }
        public virtual ICollection<TreinamentoDados> TreinamentoDados { get; set; }
        public virtual ICollection<ValidacaoDados> Validacao { get; set; }
        public virtual RedeNeuralResultante RedeNeuralResultante1 { get; set; }
        public virtual ICollection<LogTreinamento> LogTreinamento { get; set; }
    }
}
